### ISSUE TITLE
About Inference Procedure

### ISSUE THREAD

**Issue by MiZhangWhuer** [NoamRosenberg/AutoML#10]
Hi, 
    Thanks for sharing this easy understanding codes.
     Would you kindly provide the inference example when the optimal architecture is searched by decode_autodeeplab.py?
     How can I load the trained weights and the corresponding searched architecture if I want to perform inference on a single input image?
      Looking forward to your reply.

**Comment by NoamRosenberg** [comment]
@MiZhangWhuer  I've just updated the readme to try to make the process more clear. Let me know if it helps you.

About inference, that will be the last step after 1. Architecture Search 2. Decode and 3. Re-train.
once you've trained your optimal model you will do inference like any other deep learning algorithm.
