### ISSUE TITLE
gradient overflow during use of half precision 

### ISSUE THREAD

**Issue by NoamRosenberg** [NoamRosenberg/AutoML#12]
when training with half precision I receive a message:
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0
![Screen Shot 2019-08-14 at 1 21 59 PM](https://user-images.githubusercontent.com/17988235/62996248-9115af00-be96-11e9-8de8-8573fdaf01d4.png)

Is this normal ?
in any case, I'm currently testing this branch.

**Comment by iariav** [comment]
yes, it is normal. i use 

`loss_scale="dynamic"`

which means amp automatically changes the loss scale factor to prevent gradient overflow. this is precisely the message you received.
