### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 4 125 1 1, expected input[1, 128, 56, 56] to have 125 channels, but got 128 channels instead

### ISSUE THREAD

**Issue by albert-ba** [NoamRosenberg/AutoML#19]
Hi I'm running with the following command line:
CUDA_VISIBLE_DEVICES=0,1 python train_autodeeplab.py --dataset coco --filter_multiplier 4 --resize 358 --crop_size 224 --batch-size 2
This gives me:
RuntimeError: Given groups=1, weight of size 4 125 1 1, expected input[1, 128, 56, 56] to have 125 channels, but got 128 channels instead

I understand what the error about, but I can't really fix it, why I'm getting this error?

Thanks.

**Comment by NoamRosenberg** [comment]
@BBarak Hi sorry, this one is our bad. Someone merged broken code this morning. It should be working now, can you give it a try and let me know?

**Comment by BBarak** [comment]
I'm getting this error now:
"ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 20, 1, 1])" I saw in the closed issues that this was solved..

**Comment by NoamRosenberg** [comment]
@albert-ba are you using the most recent version of the code? It should be much smaller now. Would allow you to use batch 2 on a single machine.

**Comment by albert-ba** [comment]
So I changed my line to be:
"CUDA_VISIBLE_DEVICES=0 python train_autodeeplab.py --dataset coco --filter_multiplier 4 --resize 358 --crop_size 224 --batch-size 2"
And I'm getting:
  File "train_autodeeplab.py", line 356, in <module>
    main()
  File "train_autodeeplab.py", line 345, in main
    trainer = Trainer(args)
  File "train_autodeeplab.py", line 80, in __init__
    self.architect = Architect (self.model, args)
  File "./AutoML/architect.py", line 11, in __init__
    self.criterion = self.model.module._criterion
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'AutoDeeplab' object has no attribute 'module'
 
What I'm missing?

**Comment by albert-ba** [comment]
Thanks
