### ISSUE TITLE
very slow in self.model.load_state_dict(checkpoint['state_dict'])

### ISSUE THREAD

**Issue by blessxu** [NoamRosenberg/AutoML#4]
I try to reload my saved model and find it very slow with no GPU unitilization.

**Comment by NoamRosenberg** [comment]
@blessxu you are right. Currently loading models is slow, I will leave this issue open until me or someone else commits a fix.

@blessxu by the way, happy to have you contribute to the project, as well as to this specific issue. I've also got a slack group forming of potential contributors if thats something you are interested in. We have big ideas for the project.

**Comment by zhizhangxian** [comment]
When I test the model saved, I found some keys will be missed( but i can't make sure they were missed in save or load).....

**Comment by zhizhangxian** [comment]
use this function inplace torch.load_state_dict() can speed up for many times
def copy_state_dict(cur_state_dict, pre_state_dict, prefix = ''):
    def _get_params(key):
        key = prefix + key
        if key in pre_state_dict:
            return pre_state_dict[key]
        return None
    
    for k in cur_state_dict.keys():
        v = _get_params(k)
        try:
            if v is None:
                print('parameter {} not found'.format(k))
                continue
            cur_state_dict[k].copy_(v)
        except:
            print('copy param {} failed'.format(k))
            continue




@NoamRosenberg when saving the model, self._alpha won't be saved. so the result cann't be repeated if you don't test your model after training in each epoch. (I test this in pytorch1.1 and 0.4.0)
 it confused me for many days.......

**Comment by NoamRosenberg** [comment]
@zhizhangxian you are right. I fixed this just recently.

**Comment by NoamRosenberg** [comment]
@zhizhangxian this is my wechat ID: BuffalNoam. would you mind adding me? I'm interested to hear what parameters you ran and what GPU you used, as well as some other things.

**Comment by zhizhangxian** [comment]
I can's found your wechat ID in my phone.... Maybe you can find me... 
Wechat:15850629008 or zzx_299
