### ISSUE TITLE
channel mismatch and downsample setting in new_model.py

### ISSUE THREAD

**Issue by JingweiZhang12** [NoamRosenberg/AutoML#45]
1. I found a error in new_models.py
original code:
[previous channel parameter](https://github.com/NoamRosenberg/AutoML/blob/master/new_model.py#L148)
It causes channel mismatch in model forward when i ==1:
`expected input to have 40 channels, but got 80 channels instead
`
When I changed them to **self._filter_multiplier * filter_param_dict[prev_level]**, it can work.

2. I have a question about the code [downsamples setting in the first layer](https://github.com/NoamRosenberg/AutoML/blob/master/new_model.py#L135). I want to know why you force the downup_sample==0 rather than following the searched architect parameters.

**Comment by NoamRosenberg** [comment]
Hi @JingweiZhang12 looks like your correct. This section of the code still needs some work. I would love for you to create a pull request with your fixes and become a contributor of the project. Please add my WeChat BuffaloNoam, or email me and we can discuss possible collaboration on this project.
