### ISSUE TITLE
Problem in Viterbi algorithm

### ISSUE THREAD

**Issue by mrluin** [NoamRosenberg/AutoML#71]
Hi, 

Thanks for your works!
But I have some question about Viterbi Algorithm in decoding_formulas.py

I think the shape of self.network_space is [layers, scales, choices], that is layers, samples, and rates in the for loops, right?
If so, should be code [in line 50 ](https://github.com/NoamRosenberg/AutoML/blob/new_master/decoding_formulas.py#L50) is
```
if (sample == 0 and  rate == 0) or (sample == 3 and rate == 2):
    continue
```
because the corresponding choices of rate 0, 1, 2 are ↗, →, and ↘. 
If I am wrong, could you give me some hints and further explanations?
Thanks in advance.

Best regards,
TTB

**Comment by zzx-zhangxian** [comment]
Yes, you are right. Thanks very much ! :)

**Comment by zzx-zhangxian** [comment]
Sorry, I din't check the code before and make a mistake
sample == 3 rate == 0 denotes the information flow will come from the sample==4 in previous layer, it is wrong, and same as sample == 0  rate == 0
So it shold be 
```
if (sample == 0 and  rate == 2) or (sample == 3 and rate == 0):
    continue
```
Thanks ：）
