### ISSUE TITLE
Problem in viterbi_decode 

### ISSUE THREAD

**Issue by HeathHose** [NoamRosenberg/AutoML#73]
viterbi 实现有问题吧

```python
if (sample == 0 and rate == 2) or (sample == 3 and rate == 0):
      continue
```
第layer层，第0个细胞，不能进行的是0(上采样)
第layer层，第3个细胞，不能进行的是2(下采样)
应该是修改成这样的
if (sample == 0 and rate == 0) or (sample == 3 and rate == 2):
      continue

但是我修改成这样后，直接报错了。

> https://github.com/NoamRosenberg/AutoML/issues/71
这里提到的sample == 3 rate == 0 denotes the information flow will come from the sample==4 in previous layer
第layer层，第3个细胞，不能由  第4层的细胞进行上采样 得到； 

这里数据流向  和我不一样，到底哪个是对的呢

**Comment by zzx-zhangxian** [comment]
这个意思有点歧义，计算prob_space[layer][sample]过程中用的rate，也就是，下文中的rate
```
if (sample == 0 and rate == 2) or (sample == 3 and rate == 0):
      continue
```
表示的是前一层的信息来源，sample == 0 and rate == 2 表示的是，当前的level_4的feature map不可能是前一层的下采样过来(2表示下采样)
而```self.network_space[layer][sample][rate]```中的rate表示的是当前cell的信息流动方式，这两个的含义是有一些区别的，```self.network_space```的含义是来源于paper的公式(7)，prob_space中sample rate的记发是为了方便计算维特比解耦的结果：）

**Comment by HeathHose** [comment]
@zhizhangxian  thanks for your reply!
