### ISSUE TITLE
confusion in implementation of decoded network

### ISSUE THREAD

**Issue by mrluin** [NoamRosenberg/AutoML#75]
Hi, 
Thanks for your implementation!
I have some confusion in the implementation of the decoded network. 
I knew that each cell has two inputs from prev_prev_cell and prev_cell. But what the case in the decoded network. I mean that: If layer_i has downsampling rate 16, but layer_{i-1} has downsampling rate 4. In this case, prev_prev_c is None and only has prev_c's output as input, right? (from the paper, I saw that prev_prev_c's output should have the same scale as the current layer).
Could you give me some hints? Thanks in advance.

**Comment by zzx-zhangxian** [comment]
If lay_i havs downsampling 16 then it will only get information from lay_{i-1} with sample 8 and 16 not 4

**Comment by mrluin** [comment]
Thank you for your quick answer! @zhizhangxian 
I have another question about `affine` of BN in train_search phase and retrain phase. From darts, the learnable parameters of BN are disabled in train_search phase. But in some other paper like proxylessNAS, `affine` of BN is not set specifically. What effect do you think `affine` mode of BN might have?
Looking forward to your reply!

**Comment by zzx-zhangxian** [comment]
In our experiment, we set affine to False in search and True in retrain
False in search is accroding toi darts
True in retrain is accroding to deeplab v3+
