### ISSUE TITLE
Where is "make_data_loader"of dataloaders in train_autodeeplab.py

### ISSUE THREAD

**Issue by CocoRLin** [NoamRosenberg/AutoML#9]
Where is "make_data_loader"of dataloaders in train_autodeeplab.py
Thank you for answer.

**Comment by NoamRosenberg** [comment]
line 49

**Comment by CocoRLin** [comment]
> line 49

sorry, I mean where is 'make_data_loader' this function or class or make_data_loader.py

**Comment by iariav** [comment]
dataloaders -> datasets -> __init__.py
